andyair/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('account/', include('account.urls',namespace='account')),
    path('custadv/', include('custadv.urls', namespace='custadv')),
    path('custcsn/', include('custcsn.urls', namespace='custcsn')),
    path('shpr/', include('shpr.urls', namespace='shpr')),
    path('inprmk/', include('inprmk.urls', namespace='inprmk')),
    path('inpfee/', include('inpfee.urls', namespace='inpfee')),
    path('cneecrd/', include('cneecrd.urls', namespace='cneecrd')),
    path('invpars/', include('invpars.urls', namespace='invpars')),
    path('exrate/', include('exrate.urls', namespace='exrate')),
    path('awbin/', include('awbin.urls', namespace='awbin')),
    re_path('.*', views.main),
]

awbin/urls.py
from django.urls import path
from awbin import views

app_name = 'awbin'
urlpatterns = [
    path('', views.mawbinList, name='mawbinList'),
    path('mawbinList/', views.mawbinList, name='mawbinList'),
    path('mawbinCreate/',views.mawbinCreate, name='mawbinCreate'),
    path('mawbinView/<int:pk>/', views.mawbinView, name='mawbinView'),
    path('mawbinUpdate/<int:pk>/', views.mawbinUpdate, name='mawbinUpdate'),
    path('mawbinDelete/<int:pk>/', views.mawbinDelete, name='mawbinDelete'),
    path('hawbinList/<int:parent_pk>/', views.hawbinList, name='hawbinList'),
    path('hawbinCreate/<int:parent_pk>/', views.hawbinCreate, name='hawbinCreate'),
    path('hawbinView/<int:pk>/', views.hawbinView, name='hawbinView'),
    path('hawbinUpdate/<int:pk>/', views.hawbinUpdate, name='hawbinUpdate'),
    path('hawbinDelete/<int:pk>/', views.hawbinDelete, name='hawbinDelete'),
    path('dbnoteNew/<int:parent_pk>/', views.dbnoteNew, name='dbnoteNew'),
    path('debitTabledit/', views.debitTabledit, name='debitTabledit'),
    path('cdnoteNew/<int:parent_pk>/', views.cdnoteNew, name='cdnoteNew'),
    path('creditTabledit/', views.creditTabledit, name='creditTabledit'),
    path('remarkNew/<int:parent_pk>/', views.remarkNew, name='remarkNew'),
    path('remarkTabledit/', views.remarkTabledit, name='remarkTabledit'),
    # path('codNew/<int:parent_pk>/', views.codNew, name='codNew'),
    path('codTabledit/', views.codTabledit, name='codTabledit'),
]

base/urls.py
from django.urls import path
from main import views as mainViews
from base import views

app_name = 'base'
urlpatterns = [
    path('', mainViews.main, name='base'),
    path('custadvList/', views.custadvList, name='custadvList'),
    path('custadvCreate/', views.custadvCreate, name='custadvCreate'),
    path('custadvView/<int:pk>/', views.custadvView, name='custadvView'),
    path('custadvUpdate/<int:pk>/', views.custadvUpdate, name='custadvUpdate'),
    path('custadvDelete/<int:pk>/', views.custadvDelete, name='custadvDelete'),
    path('custqtnTabledit/', views.custqtnTabledit, name='custqtnTabledit'),
    path('custqtnNew/<int:parent_pk>/', views.custqtnNew, name='custqtnNew'),
    path('custadvData/<int:pk>/', views.custadvData, name='custadvData'),
]

awbin/models.py
from django.db import models
from custcsn.models import Custcsn
from custadv.models import Custadv
from shpr.models import Shpr
from main.models import OrgDest
# from inpfee.models import Inpfee
# from exrate.models import Exrate
from main.models import WhoColumns


class Mawbin(WhoColumns):
    mawb = models.CharField(max_length=12, unique=True)
    seqnr = models.CharField(max_length=15, blank=True)
    prsdd = models.DateField(blank=True)
    nrhbhold = models.IntegerField(default=0, null=True, blank=True)
    podfax = models.CharField(max_length=1, blank=True)
    agtcode = models.ForeignKey(Custcsn, on_delete=models.DO_NOTHING, max_length=6, blank=True, null=True)
    mfrom = models.ForeignKey(OrgDest, on_delete=models.DO_NOTHING, max_length=3, blank=True, null=True)
    mdepdd = models.DateField(blank=True)
    metaflt = models.CharField(max_length=7, blank=True)
    metadd = models.DateField(blank=True)
    marvflt = models.CharField(max_length=7, blank=True)
    marvdd = models.DateField(blank=True)
    mpuawbdd = models.DateField(blank=True)
    mcusdept = models.CharField(max_length=2, blank=True)
    msvcknd = models.CharField(max_length=1, blank=True)
    marvapt = models.CharField(max_length=5, blank=True)
    munlodwh = models.CharField(max_length=6, blank=True)
    nrofhawb = models.IntegerField(default=0, null=True, blank=True)
    mpkgnr = models.IntegerField(default=0, null=True, blank=True)
    mpkgunit = models.CharField(max_length=6, blank=True)
    mgw = models.DecimalField(max_digits=7, decimal_places=1, null=True,blank=True)
    mgwunit = models.CharField(max_length=3, blank=True)
    mchgwt = models.DecimalField(max_digits=7, decimal_places=1, null=True,blank=True)
    mchgunit = models.CharField(max_length=3, blank=True)
    mkgchgwt = models.DecimalField(max_digits=7, decimal_places=1, null=True,blank=True)
    mccpp = models.CharField(max_length=2, blank=True)
    mcurncy = models.CharField(max_length=3, blank=True, null=True)
    mexchg = models.DecimalField(max_digits=9, decimal_places=5, null=True,blank=True)
    mfrtrte = models.DecimalField(max_digits=6, decimal_places=2, null=True,blank=True)
    mwtchrg = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    mwtchtwd = models.DecimalField(max_digits=9, decimal_places=2, null=True,blank=True)
    mduagt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    mducar = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    mttlfrt = models.DecimalField(max_digits=11, decimal_places=2, null=True,blank=True)
    mtlfrtwd = models.DecimalField(max_digits=9, decimal_places=2, null=True,blank=True)
    rdbnr = models.IntegerField(default=0, null=True, blank=True)
    rcdnr = models.IntegerField(default=0, null=True, blank=True)
    trsdbnr = models.IntegerField(default=0, null=True, blank=True)
    dtddbnr = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.mawb + '-' + self.seqnr

class Hawbin(WhoColumns):
    mawb = models.ForeignKey(Mawbin, on_delete=models.CASCADE)
    hawb = models.CharField(max_length=12)
    hlotnr = models.CharField(max_length=9, blank=True)
    belong = models.CharField(max_length=9, blank=True)
    nrofshb = models.IntegerField(default=0, null=True, blank=True)
    pkgofhb = models.IntegerField(default=0, null=True, blank=True)
    hseqnr = models.CharField(max_length=4, blank=True)
    hshpr = models.ForeignKey(Shpr, on_delete=models.DO_NOTHING, max_length=6, blank=True, null=True)
    hcnee = models.ForeignKey(Custcsn, on_delete=models.DO_NOTHING, max_length=6, blank=True, null=True)
    hnotify = models.ForeignKey(Custadv, on_delete=models.DO_NOTHING, max_length=6, blank=True, null=True)
    hfrom = models.ForeignKey(OrgDest, on_delete=models.DO_NOTHING, max_length=3, blank=True, null=True)
    hrlsdd = models.DateTimeField(blank=True)
    # hrlstm = models.TimeField(blank=True)
    ro = models.CharField(max_length=1, default="N", blank=True)
    hslsman = models.CharField(max_length=2, blank=True)
    hacct = models.CharField(max_length=1, default="N", blank=True)
    trans = models.CharField(max_length=1, default="N", blank=True)
    fnldest = models.CharField(max_length=3, blank=True)
    trsdb = models.CharField(max_length=6, blank=True)
    cusapp = models.CharField(max_length=1, default="N", blank=True)
    dtd = models.CharField(max_length=1, default="N", blank=True)
    dtddb = models.CharField(max_length=6, blank=True)
    hgoods = models.CharField(max_length=150, blank=True)
    skdpk = models.CharField(max_length=3, default="N  ", blank=True)
    hpkgnr = models.IntegerField(default=0, null=True, blank=True)
    hpkgunit = models.CharField(max_length=3, default="CTN", blank=True)
    hgw = models.DecimalField(max_digits=7, decimal_places=1, null=True,blank=True)
    hgwunit = models.CharField(max_length=3, default="KGS", blank=True)
    hchgwt = models.DecimalField(max_digits=7, decimal_places=1, null=True,blank=True)
    hchgunit = models.CharField(max_length=3, default="KGS", blank=True)
    hkgchgwt = models.DecimalField(max_digits=7, decimal_places=1, null=True,blank=True)
    hccpp = models.CharField(max_length=2, default="PP", blank=True)
    hcurncy = models.CharField(max_length=3, blank=True, null=True)
    hexchg = models.DecimalField(max_digits=9, decimal_places=5, null=True,blank=True)
    hfrtrte = models.DecimalField(max_digits=6, decimal_places=2, null=True,blank=True)
    hwtchrg = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    hduagt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    httlfrt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    htlfrtwd = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    vwdspct = models.DecimalField(max_digits=4, decimal_places=2, null=True,blank=True)
    vwdskglb = models.DecimalField(max_digits=6, decimal_places=2, null=True,blank=True)
    vwdsper = models.CharField(max_length=2, blank=True)
    ttldsamt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    ttldstwd = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    hflfrtwd = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    hpayby = models.CharField(max_length=1, default="K", blank=True)
    howe = models.IntegerField(default=0, null=True, blank=True)
    hadvsdd = models.DateField(blank=True)
    sccurn =  models.CharField(max_length=3, blank=True, null=True)
    scpct = models.DecimalField(max_digits=4, decimal_places=2, null=True,blank=True)
    scpkls = models.DecimalField(max_digits=6, decimal_places=2, null=True,blank=True)
    scper = models.CharField(max_length=2, blank=True, null=True)
    scamt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    scamtwd = models.DecimalField(max_digits=8, decimal_places=2, null=True,blank=True)
    sctowho = models.CharField(max_length=12, blank=True, null=True)
    codcurn = models.CharField(max_length=3, blank=True, null=True)
    codamt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    codrcvdd = models.DateField(blank=True)
    codpaydd = models.DateField(blank=True)
    hrmk = models.CharField(max_length=1, blank=True, null=True)
    hdb = models.CharField(max_length=1, default="P", blank=True)
    hcd = models.CharField(max_length=1, default="P", blank=True)
    httlamt = models.DecimalField(max_digits=9, decimal_places=2, null=True,blank=True)
    ttlocamt = models.DecimalField(max_digits=9, decimal_places=2, null=True,blank=True)
    # dbcurn = models.CharField(max_length=3, blank=True, null=True)
    # dbexrate = models.DecimalField(max_digits=9, decimal_places=5, null=True,blank=True)
    # dbamount = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)

    class Meta:
        unique_together = (('mawb', 'hawb'),)

    def __str__(self):
        return self.hawb + '-' + self.hlotnr

class Acctin(WhoColumns):
    mawb = models.ForeignKey(Mawbin, on_delete=models.DO_NOTHING, blank=True, null=True)
    hawb = models.ForeignKey(Hawbin, on_delete=models.DO_NOTHING, blank=True, null=True)
    dc = models.CharField(max_length=1, blank=True, null=True)
    dcno = models.CharField(max_length=9, unique=True)
    dccurn = models.CharField(max_length=3, blank=True, null=True)
    exrate1 = models.DecimalField(max_digits=9, decimal_places=5, null=True,blank=True)
    dcamt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    issdd = models.DateField(null=True,blank=True)
    status0 = models.CharField(max_length=1, blank=True, null=True)
    status1 = models.CharField(max_length=1, blank=True, null=True)
    status2 = models.CharField(max_length=1, blank=True, null=True)
    status3 = models.CharField(max_length=1, blank=True, null=True)
    rcvdd = models.DateField(null=True,blank=True)
    rcvamt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    balamt = models.DecimalField(max_digits=10, decimal_places=2, null=True,blank=True)
    payclr = models.CharField(max_length=1, blank=True, null=True)
    actagno1 = models.ForeignKey(Custcsn, on_delete=models.DO_NOTHING, max_length=6, blank=True, null=True)

    def __str__(self):
        return  self.dcno + ' - ' + str(self.dcamt)

class Rmkin(WhoColumns):
    mawb = models.ForeignKey(Mawbin, on_delete=models.DO_NOTHING, blank=True, null=True)
    hawb = models.ForeignKey(Hawbin, on_delete=models.DO_NOTHING, blank=True, null=True)
    codr = models.CharField(max_length=3)
    statement = models.CharField(max_length=60)
    irrno = models.CharField(max_length=2)

    def __str__(self):
        return  self.codr + ' - ' + self.statement

class Accin(WhoColumns):

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from base.models import Custadv, Custqtn
from base.forms import CustadvForm, CustqtnForm

@login_required
def custadvList(request, template_name='base/custadvList.html'):
    custadvs = Custadv.objects.all()
    ctx = {}
    ctx['custadvs'] = custadvs
    ctx['title'] = 'List'
    return render(request, template_name, ctx)

@login_required
def custadvCreate(request, template_name='base/custadvForm.html'):
    form = CustadvForm(request.POST or None)
    if form.is_valid():
        new_cust = form.save(commit=False)
        new_cust.created_by = request.user
        new_cust.last_updated_by = request.user
        new_cust.save()
        messages.success(request, '資料已新增！')
        return redirect('base:custadvUpdate', new_cust.id)
    ctx = {}
    ctx['form'] = form
    ctx['title'] = 'New'
    return render(request, template_name, ctx)

@login_required
def custadvView(request, pk, template_name='base/custadvView.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'View'
    return render(request, template_name, ctx)

@login_required
def custadvUpdate(request, pk, template_name='base/custadvForm.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    form = CustadvForm(request.POST or None, instance=custadv)
    if form.is_valid():
        custadv_obj = form.save(commit=False)
        custadv_obj.last_updated_by = request.user
        custadv_obj.save()
        messages.success(request, '資料已更新！')
        return redirect('base:custadvUpdate', custadv.id)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['form'] = form
    ctx['title'] = 'Edit'
    return render(request, template_name, ctx)

@login_required
def custadvDelete(request, pk, template_name='base/custadvDelete.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    if request.method == 'POST':
        custadv.delete()
        messages.success(request, '資料已刪除！')
        return redirect('base:custadvList')
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'Delete'
    return render(request, template_name, ctx)

@login_required
def custadvData(request, pk):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    if request.POST.get('requestData') == 'master':
        ctx['custadv'] = custadv
        template_name = 'base/custMaster.html'
    else:
        ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
        template_name = 'base/custDetail.html'
    return render(request, template_name, ctx)

@login_required
def custqtnNew(request, parent_pk, template_name='base/custqtnNew.html'):
    custadv = get_object_or_404(Custadv, pk=parent_pk)
    form = CustqtnForm(request.POST or None)
    if form.is_valid():
        custqtn = form.save(commit=False)
        custqtn.custadv = custadv
        custqtn.created_by = request.user
        custqtn.last_updated_by = request.user
        custqtn.save()
        messages.success(request, '明細資料已新增！')
        return redirect('base:custadvUpdate', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["custadv"] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = ' New Detail'
    return render(request, template_name, ctx)

@login_required
def custqtnTabledit(request):
    if request.method == 'POST':
        custqtn = get_object_or_404(Custqtn, pk=request.POST.get('id'))
        if request.POST.get('action') == 'edit':
            custqtn.org = request.POST.get('org')
            custqtn.qtndd = datetime.strptime(request.POST.get('qtndd'),"%Y-%m-%d").date()
            custqtn.qtns = request.POST.get('qtns')
            custqtn.last_updated_by = request.user
            custqtn.save()
            messages.success(request, '明細資料已更新！')
        if request.POST.get('action') == 'delete':
            custqtn.delete()
            messages.success(request, '明細資料已刪除！')

        django_messages = []
        for message in messages.get_messages(request):
            django_messages.append({
                "level": message.level,
                "message": message.message,
                "tags": message.tags,
            })
        ctx = {}
        ctx['request'] = request.POST
        ctx['messages'] = django_messages

        return JsonResponse(ctx)
        # return JsonResponse(request.POST)
    else:
        return render(request, 'main/main.html')

awbin/templates/awbin/hawbinDelete.html
{% extends "awbin/base.html" %}

{% block app_content %}

{% include "awbin/nav.html" with mawbin=mawbin title=title %}
{% include 'main/messages.html' %}

  <div class="btn-group btn-group-md" style="margin-top:-15px; float: right;">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mawbinDeleteModal">
      刪除此提單資料
    </button>
  </div>
<div class="col-xs-12 col-sm-12">
  <form id="masterForm" role="form" method="post">{% csrf_token %}
    {% include "awbin/mawbinInput.html" %}
  </form>
</div>

<!-- Modal -->
<div class="modal fade" id="mawbinDeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-md modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:darkslateblue;color:white;">
        <button type="button" class="close" data-dismiss="modal" style="color:white;">&times;</button>
        <h4 class="modal-title"><span class="glyphicon glyphicon-trash">&nbsp;提單資料刪除</span></h4>
      </div>
      <div id="div_messages" class="text-center align-middle" style="height: 40px"></div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
             <form method="post" action="{% url 'awbin:mawbinDelete' mawbin.id %}">{% csrf_token %}
                <h3>{{ mawbin }}
                  <p class="text-danger blinking"><strong>確定要刪除此提單資料 ? </strong></p><br>
                  <input class="btn btn-danger btn-md" type="submit" value="確定刪除" />
                  <a class="btn btn-primary btn-md" href="{% url 'awbin:mawbinList' %}">取消</a>
                </h3>
            </form>
          </div>
        </div>
      </div>
        <div class="modal-footer">
          <div class="text-center">
            <input type="button" value="Close" class="btn btn-md btn-secondary pull-right" data-dismiss="modal" />
          </div>
        </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
      $('#masterForm :input').prop('readonly',true);
      $('#id_agtcode').attr("disabled", true);
      $('#id_mfrom').attr("disabled", true);
      $('#id_mcusdept').attr("disabled", true);
      $('#id_msvcknd').attr("disabled", true);
      $('#id_marvapt').attr("disabled", true);
      $('#id_munlodwh').attr("disabled", true);
      $('#id_mpkgunit').attr("disabled", true);
      $('#id_mgwunit').attr("disabled", true);
      $('#id_mchgunit').attr("disabled", true);
      $('#id_mccpp').attr("disabled", true);
      $('#id_mcurncy').attr("disabled", true);
      $('#masterForm select').children('option').attr('disabled', true);
      
      function blinker() {
        $('.blinking').fadeOut(500);
        $('.blinking').fadeIn(500);
      }
      setInterval(blinker, 1000);
      
  });
</script>
{% endblock app_content %}

awbin/templates/awbin/hawbinView.html
{% extends "awbin/base.html" %}

{% block app_content %}

{% include "awbin/nav.html" with mawbin=mawbin title=title %}

  <div class="btn-group btn-group-md" style="margin-top:-15px; float: right;">
    <a href="{% url 'awbin:mawbinUpdate' mawbin.id %}" class="tabledit-edit-button btn btn-md btn-primary active"><span class="glyphicon glyphicon-pencil"></span></a>
    <a href="{% url 'awbin:mawbinDelete' mawbin.id %}" class="tabledit-delete-button btn btn-md btn-warning active"><span class="glyphicon glyphicon-trash"></span></a>
  </div>
<div class="col-xs-12 col-sm-12">
  <form id="masterForm" role="form" method="post">{% csrf_token %}
    {% include "awbin/mawbinInput.html" %}
  </form>
</div>
<script>
  $(document).ready(function(){
      $('#masterForm :input').prop('readonly',true);
      $('#id_agtcode').attr("disabled", true);
      $('#id_mfrom').attr("disabled", true);
      $('#id_mcusdept').attr("disabled", true);
      $('#id_msvcknd').attr("disabled", true);
      $('#id_marvapt').attr("disabled", true);
      $('#id_munlodwh').attr("disabled", true);
      $('#id_mpkgunit').attr("disabled", true);
      $('#id_mgwunit').attr("disabled", true);
      $('#id_mchgunit').attr("disabled", true);
      $('#id_mccpp').attr("disabled", true);
      $('#id_mcurncy').attr("disabled", true);
      $('#masterForm select').children('option').attr('disabled', true);
      
  });
</script>
{% endblock app_content %}

awbin/templates/awbin/mawbinDelete.html
{% extends "awbin/base.html" %}

{% block app_content %}

{% include "awbin/nav.html" with mawbin=mawbin title=title %}
{% include 'main/messages.html' %}

  <div class="btn-group btn-group-md" style="margin-top:-15px; float: right;">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mawbinDeleteModal">
      刪除此提單資料
    </button>
  </div>
<div class="col-xs-12 col-sm-12">
  <form id="masterForm" role="form" method="post">{% csrf_token %}
    {% include "awbin/mawbinInput.html" %}
  </form>
</div>

<!-- Modal -->
<div class="modal fade" id="mawbinDeleteModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-md modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:darkslateblue;color:white;">
        <button type="button" class="close" data-dismiss="modal" style="color:white;">&times;</button>
        <h4 class="modal-title"><span class="glyphicon glyphicon-trash">&nbsp;提單資料刪除</span></h4>
      </div>
      <div id="div_messages" class="text-center align-middle" style="height: 40px"></div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
             <form method="post" action="{% url 'awbin:mawbinDelete' mawbin.id %}">{% csrf_token %}
                <h3>{{ mawbin }}
                  <p class="text-danger blinking"><strong>確定要刪除此提單資料 ? </strong></p><br>
                  <input class="btn btn-danger btn-md" type="submit" value="確定刪除" />
                  <a class="btn btn-primary btn-md" href="{% url 'awbin:mawbinList' %}">取消</a>
                </h3>
            </form>
          </div>
        </div>
      </div>
        <div class="modal-footer">
          <div class="text-center">
            <input type="button" value="Close" class="btn btn-md btn-secondary pull-right" data-dismiss="modal" />
          </div>
        </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function(){
      $('#masterForm :input').prop('readonly',true);
      $('#id_agtcode').attr("disabled", true);
      $('#id_mfrom').attr("disabled", true);
      $('#id_mcusdept').attr("disabled", true);
      $('#id_msvcknd').attr("disabled", true);
      $('#id_marvapt').attr("disabled", true);
      $('#id_munlodwh').attr("disabled", true);
      $('#id_mpkgunit').attr("disabled", true);
      $('#id_mgwunit').attr("disabled", true);
      $('#id_mchgunit').attr("disabled", true);
      $('#id_mccpp').attr("disabled", true);
      $('#id_mcurncy').attr("disabled", true);
      $('#masterForm select').children('option').attr('disabled', true);
      
      function blinker() {
        $('.blinking').fadeOut(500);
        $('.blinking').fadeIn(500);
      }
      setInterval(blinker, 1000);
      
  });
</script>
{% endblock app_content %}

awbin/templates/awbin/mawbinView.html
{% extends "awbin/base.html" %}

{% block app_content %}

{% include "awbin/nav.html" with mawbin=mawbin title=title %}

  <div class="btn-group btn-group-md" style="margin-top:-15px; float: right;">
    <a href="{% url 'awbin:mawbinUpdate' mawbin.id %}" class="tabledit-edit-button btn btn-md btn-primary active"><span class="glyphicon glyphicon-pencil"></span></a>
    <a href="{% url 'awbin:mawbinDelete' mawbin.id %}" class="tabledit-delete-button btn btn-md btn-warning active"><span class="glyphicon glyphicon-trash"></span></a>
  </div>
<div class="col-xs-12 col-sm-12">
  <form id="masterForm" role="form" method="post">{% csrf_token %}
    {% include "awbin/mawbinInput.html" %}
  </form>
</div>
<script>
  $(document).ready(function(){
      $('#masterForm :input').prop('readonly',true);
      $('#id_agtcode').attr("disabled", true);
      $('#id_mfrom').attr("disabled", true);
      $('#id_mcusdept').attr("disabled", true);
      $('#id_msvcknd').attr("disabled", true);
      $('#id_marvapt').attr("disabled", true);
      $('#id_munlodwh').attr("disabled", true);
      $('#id_mpkgunit').attr("disabled", true);
      $('#id_mgwunit').attr("disabled", true);
      $('#id_mchgunit').attr("disabled", true);
      $('#id_mccpp').attr("disabled", true);
      $('#id_mcurncy').attr("disabled", true);
      $('#masterForm select').children('option').attr('disabled', true);
      
  });
</script>
{% endblock app_content %}

awbin/templates/awbin/nav.html
<h4 class="mt-0">
<a href="/">主選單</a>&gt;
<a href="{% url 'awbin:mawbinList' %}"> 主提單列表</a>
{% if mawbin %}
  &gt; <a href="{% url 'awbin:mawbinView' mawbin.id %}">{{ mawbin.mawb }} {{ mawbin.seqnr }}</a>
{% endif %}
{% if title %}
    -&nbsp;{{ title }}
{% endif %}
</h4>
<hr class="mt-0">