andyair/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('account/', include('account.urls',namespace='account')),
    path('custadv/', include('custadv.urls', namespace='custadv')),
    path('custcsn/', include('custcsn.urls', namespace='custcsn')),
    path('shpr/', include('shpr.urls', namespace='shpr')),
    path('inprmk/', include('inprmk.urls', namespace='inprmk')),
    path('inpfee/', include('inpfee.urls', namespace='inpfee')),
    path('cneecrd/', include('cneecrd.urls', namespace='cneecrd')),
    path('invpars/', include('invpars.urls', namespace='invpars')),
    path('exrate/', include('exrate.urls', namespace='exrate')),
    path('awbin/', include('awbin.urls', namespace='awbin')),
    re_path('.*', views.main),
]

awbin/urls.py
from django.urls import path
from awbin import views

app_name = 'awbin'
urlpatterns = [
    path('', views.mawbinList, name='mawbinList'),
    path('mawbinList/', views.mawbinList, name='mawbinList'),
    path('mawbinCreate/',views.mawbinCreate, name='mawbinCreate'),
    path('mawbinView/<int:pk>/', views.mawbinView, name='mawbinView'),
    path('mawbinUpdate/<int:pk>/', views.mawbinUpdate, name='mawbinUpdate'),
    path('mawbinDelete/<int:pk>/', views.mawbinDelete, name='mawbinDelete'),
    path('hawbinList/<int:parent_pk>/', views.hawbinList, name='hawbinList'),
    path('hawbinCreate/<int:parent_pk>/', views.hawbinCreate, name='hawbinCreate'),
    path('hawbinView/<int:pk>/', views.hawbinView, name='hawbinView'),
    path('hawbinUpdate/<int:pk>/', views.hawbinUpdate, name='hawbinUpdate'),
    path('hawbinDelete/<int:pk>/', views.hawbinDelete, name='hawbinDelete'),
    path('dbnoteNew/<int:parent_pk>/', views.dbnoteNew, name='dbnoteNew'),
    path('debitTabledit/', views.debitTabledit, name='debitTabledit'),
    path('cdnoteNew/<int:parent_pk>/', views.cdnoteNew, name='cdnoteNew'),
    path('creditTabledit/', views.creditTabledit, name='creditTabledit'),
    path('remarkNew/<int:parent_pk>/', views.remarkNew, name='remarkNew'),
    path('remarkTabledit/', views.remarkTabledit, name='remarkTabledit'),
    # path('codNew/<int:parent_pk>/', views.codNew, name='codNew'),
    path('codTabledit/', views.codTabledit, name='codTabledit'),
]

base/urls.py
from django.urls import path
from main import views as mainViews
from base import views

app_name = 'base'
urlpatterns = [
    path('', mainViews.main, name='base'),
    path('custadvList/', views.custadvList, name='custadvList'),
    path('custadvCreate/', views.custadvCreate, name='custadvCreate'),
    path('custadvView/<int:pk>/', views.custadvView, name='custadvView'),
    path('custadvUpdate/<int:pk>/', views.custadvUpdate, name='custadvUpdate'),
    path('custadvDelete/<int:pk>/', views.custadvDelete, name='custadvDelete'),
    path('custqtnTabledit/', views.custqtnTabledit, name='custqtnTabledit'),
    path('custqtnNew/<int:parent_pk>/', views.custqtnNew, name='custqtnNew'),
    path('custadvData/<int:pk>/', views.custadvData, name='custadvData'),
]

exrate/urls.py
from django.urls import path
from exrate import views

app_name = 'exrate'
urlpatterns = [
    path('exrateList/', views.exrateList, name='exrateList'),
    path('exrateCreate/',views.exrateCreate, name='exrateCreate'),
    path('exrateUpdate/<int:pk>/', views.exrateUpdate, name='exrateUpdate'),
    path('exrateDelete/<int:pk>/', views.exrateDelete, name='exrateDelete'),
]

inpfee/urls.py
from django.urls import path
from inpfee import views

app_name = 'inpfee'
urlpatterns = [
    path('inpfeeList/', views.inpfeeList, name='inpfeeList'),
    path('inpfeeCreate/',views.inpfeeCreate, name='inpfeeCreate'),
    path('inpfeeView/<int:pk>/', views.inpfeeView, name='inpfeeView'),
    path('inpfeeUpdate/<int:pk>/', views.inpfeeUpdate, name='inpfeeUpdate'),
    path('inpfeeDelete/<int:pk>/', views.inpfeeDelete, name='inpfeeDelete'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
]

shpr/urls.py
from django.urls import path
from shpr import views

app_name = 'shpr'
urlpatterns = [
    path('shprList/', views.shprList, name='shprList'),
    path('shprCreate/',views.shprCreate, name='shprCreate'),
    path('shprView/<int:pk>/', views.shprView, name='shprView'),
    path('shprUpdate/<int:pk>/', views.shprUpdate, name='shprUpdate'),
    path('shprDelete/<int:pk>/', views.shprDelete, name='shprDelete'),
]

main/models.py
from django.db import models
from account.models import User

class OrgDest(models.Model):
    code5 = models.CharField(max_length=5, unique=True)
    code = models.CharField(max_length=3, unique=True)
    dest = models.CharField(max_length=30, blank=True)
    iso = models.CharField(max_length=2, blank=True)
    country = models.CharField(max_length=20, blank=True)
    aircode = models.CharField(max_length=5, blank=True)

    def __str__(self):
        return self.code + ' - ' + self.dest


class WhoColumns(models.Model):
    creation_date = models.DateTimeField(auto_now_add=True)         # 建立日期
    created_by = models.ForeignKey(User, editable=False,
                                   db_column='created_by',
                                   related_name='%(app_label)s_%(class)s_created_by',
                                   blank=True, null=True,
                                   on_delete=models.SET_NULL)    #建立者

    last_update_date = models.DateTimeField(auto_now=True)          # 最後更新日期
    last_updated_by = models.ForeignKey(User, editable=False,
                                        db_column='last_updated_by',
                                        related_name='%(app_label)s_%(class)s_last_updated_by',
                                        blank=True, null=True,
                                        on_delete=models.SET_NULL)  # 最後更新者


    # def save(self, *args, **kwargs):
    #     if not self.creation_date:
    #         self.creation_date = datetime.now()
    #
    #     self.last_update_date = datetime.now()
    #     return super(WhoColumns, self).save(*args, **kwargs)

    class Meta:
        abstract = True

base/forms.py
from django import forms
from base.models import Custadv, Custqtn


class CustadvForm(forms.ModelForm):
    cuno = forms.CharField(label='客戶代號', min_length=6, max_length=10, required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntfy = forms.CharField(label='應通知公司', max_length=30, required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntfym = forms.CharField(label='貨主聯絡人', max_length=30, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntftl = forms.CharField(label='電話號碼', max_length=20, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntffx = forms.CharField(label='傳真號碼', max_length=20, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipmnspay = forms.BooleanField(label='是否月結', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    ipentry = forms.BooleanField(label='是否報關', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    iprtord = forms.BooleanField(label='是否進口指定貨', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    ipntfmk = forms.CharField(label='備註', max_length=30, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Custadv
        fields = ['cuno', 'ipntfy', 'ipntfym', 'ipntftl', 'ipntffx', 'ipmnspay', 'ipentry', 'iprtord', 'ipntfmk']

class CustqtnForm(forms.ModelForm):

    org = forms.CharField(label='ORG', max_length=3, widget=forms.TextInput(attrs={'class':'form-control'}))
    qtndd = forms.DateField(label='日期', widget=forms.TextInput(attrs={'readonly':'readonly','class':'form-control'}))
    qtns = forms.CharField(label='說明', max_length=60, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Custqtn
        fields = ['org', 'qtndd', 'qtns']

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from base.models import Custadv, Custqtn
from base.forms import CustadvForm, CustqtnForm

@login_required
def custadvList(request, template_name='base/custadvList.html'):
    custadvs = Custadv.objects.all()
    ctx = {}
    ctx['custadvs'] = custadvs
    ctx['title'] = 'List'
    return render(request, template_name, ctx)

@login_required
def custadvCreate(request, template_name='base/custadvForm.html'):
    form = CustadvForm(request.POST or None)
    if form.is_valid():
        new_cust = form.save(commit=False)
        new_cust.created_by = request.user
        new_cust.last_updated_by = request.user
        new_cust.save()
        messages.success(request, '資料已新增！')
        return redirect('base:custadvUpdate', new_cust.id)
    ctx = {}
    ctx['form'] = form
    ctx['title'] = 'New'
    return render(request, template_name, ctx)

@login_required
def custadvView(request, pk, template_name='base/custadvView.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'View'
    return render(request, template_name, ctx)

@login_required
def custadvUpdate(request, pk, template_name='base/custadvForm.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    form = CustadvForm(request.POST or None, instance=custadv)
    if form.is_valid():
        custadv_obj = form.save(commit=False)
        custadv_obj.last_updated_by = request.user
        custadv_obj.save()
        messages.success(request, '資料已更新！')
        return redirect('base:custadvUpdate', custadv.id)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['form'] = form
    ctx['title'] = 'Edit'
    return render(request, template_name, ctx)

@login_required
def custadvDelete(request, pk, template_name='base/custadvDelete.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    if request.method == 'POST':
        custadv.delete()
        messages.success(request, '資料已刪除！')
        return redirect('base:custadvList')
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'Delete'
    return render(request, template_name, ctx)

@login_required
def custadvData(request, pk):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    if request.POST.get('requestData') == 'master':
        ctx['custadv'] = custadv
        template_name = 'base/custMaster.html'
    else:
        ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
        template_name = 'base/custDetail.html'
    return render(request, template_name, ctx)

@login_required
def custqtnNew(request, parent_pk, template_name='base/custqtnNew.html'):
    custadv = get_object_or_404(Custadv, pk=parent_pk)
    form = CustqtnForm(request.POST or None)
    if form.is_valid():
        custqtn = form.save(commit=False)
        custqtn.custadv = custadv
        custqtn.created_by = request.user
        custqtn.last_updated_by = request.user
        custqtn.save()
        messages.success(request, '明細資料已新增！')
        return redirect('base:custadvUpdate', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["custadv"] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = ' New Detail'
    return render(request, template_name, ctx)

@login_required
def custqtnTabledit(request):
    if request.method == 'POST':
        custqtn = get_object_or_404(Custqtn, pk=request.POST.get('id'))
        if request.POST.get('action') == 'edit':
            custqtn.org = request.POST.get('org')
            custqtn.qtndd = datetime.strptime(request.POST.get('qtndd'),"%Y-%m-%d").date()
            custqtn.qtns = request.POST.get('qtns')
            custqtn.last_updated_by = request.user
            custqtn.save()
            messages.success(request, '明細資料已更新！')
        if request.POST.get('action') == 'delete':
            custqtn.delete()
            messages.success(request, '明細資料已刪除！')

        django_messages = []
        for message in messages.get_messages(request):
            django_messages.append({
                "level": message.level,
                "message": message.message,
                "tags": message.tags,
            })
        ctx = {}
        ctx['request'] = request.POST
        ctx['messages'] = django_messages

        return JsonResponse(ctx)
        # return JsonResponse(request.POST)
    else:
        return render(request, 'main/main.html')

main/views.py
from django.shortcuts import render

def main(request):
    context = {'system': '空運進口提單系統'}
    context['nextURL'] = request.GET.get('next')
    return render(request, 'main/main.html', context)

main/templates/main/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{csrf_token}}">

  <title>安抵空運{% block title %}首頁{% endblock %}</title>
  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'main/css/normalize.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'main/css/bootstrap-datepicker3.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/dataTables.bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main/css/main.css' %}">

    <!--JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="{% static 'main/js/csrf.js' %}"></script>
  <script src="{% static 'main/js/jquery.tabledit.min.js' %}"></script>
  <script src="{% static 'main/js/moment.js' %}"></script>
  <script src="{% static 'main/js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'main/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'main/js/dataTables.bootstrap.min.js' %}"></script>
  {% block extra_style%} {% endblock %}
  {% block extra_js%} {% endblock %}
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">安抵空運代理股有限公司</a>
      </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li class="active"><a href="#">進口提單</a></li>
        <li><a href="/">......</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li><a href="{% url 'account:userUpdate' user.id %}">Welcome {{ user.username }}({{user.fullname}})</a></li>
          <li><a href="{% url 'account:logout' %}"><span class="glyphicon glyphicon-log-out"></span> 登出</a></li>
        {% else %}
          <li><a id="login" href="#" data-form="{% url 'account:login' %}" title="Login" data-toggle="modal">
            <span class="glyphicon glyphicon-log-in"></span> 登入</a></li>
          <li><a href="{% url 'account:userCreate' %}"><span class="glyphicon glyphicon-user"></span> 註冊</a></li>
          {% if nextURL %}
            <script>
                setTimeout(function() {
                    document.getElementById('login').click();
                }, 500);
            </script>
          {% endif %}
        {% endif %}
      </ul>
    </div>

  </nav>
  <br>

  <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <!--<div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-hidden="true"></div>-->

{% block content %}  {% endblock %}
  <footer class="navbar-fixed-bottom">
    <small style="text-align:center;">&nbsp;&nbsp;&copy; 2018 ANDY Air Transport Co., Ltd. | ADMIRAL Freight Service Inc. 台北市內湖區瑞光路66巷23號3樓(台北內湖科技園區)</small>
  </footer>
<script>
    $(document).ready(function(){

        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });

        $(".alert").fadeOut(3000);
        
        $("#login").bind('click',function(event) {
            event.preventDefault(); // prevent navigation
            var url = $(this).data("form"); // get the login form url
            $("#loginModal").load(url, function() { // load the url into the modal
                $(this).modal('show'); // display the modal on url load

            });
            return false; // prevent the click propagation
        });
        
        $('#loginModal').on('submit', '#loginForm', function() {
            $.ajax({
                type: $(this).attr('method'),
                url: this.action,
                data: $(this).serialize() + '&nextURL=' + '{{ nextURL }}',
                context: this,
                success: function(data, status) {
                    update_messages(data.messages);
                    $(".alert").fadeOut(3000);
                    if (data.result === 'Failure') {
                        //  alert('登入失敗');
                        
                    } else {
                        // alert('登入成功');
                        setTimeout(function() {
                            $('#loginModal').modal('hide');
                            // location.reload(); },
                            location.assign('{{ nextURL }}'); },
                            500);
                    }
                    console.log("success");
                    console.log(data);
                    console.log(data.result);
                },
                error: function (request, status, error) {
                    console.log("failure");
                    console.log(request.responseText);
                }
            });
            return false;
        });
        
    });
    function update_messages(messages) {
        $("#div_messages").html("");
        $.each(messages, function (i, m) {
            var html = "<div class='alert alert-"+m.tags+" alert-dismissible fade in'>"+"<strong>"+m.message+"</strong>"+"</div>";
            $("#div_messages").append(html);
        });
    }
</script>

</body>
</html>

main/templates/main/main.html
{% extends 'main/base.html' %}

{% block content %}

{% include 'main/menu.html' %}
{% include 'main/messages.html' %}
{% endblock %}

main/templates/main/menu.html
{% block content %}
    <div class="container">
      <br><br>
      <h2 style="text-align:center">{{ system }}</h2>
      <div class="row">
        <div class="col-md-4">
          <h3 style="background-color:darkorange; color:white; text-align:center; border-radius:25px; padding:5px;">提單資料維護</h3>
          <div class="list-group">
              <a href="{% url 'awbin:mawbinList' %}" class="list-group-item h4">進 口 提 單 資 料 維 護</a>
              <a href="#" class="list-group-item h4">進 口 發 單 資 料 清 表</a>
              <a href="#" class="list-group-item h4">進 口 發 票 管 理 作 業</a>
              <a href="#" class="list-group-item h4">進 口 發 單 作 業</a>
              <a href="#" class="list-group-item h4">進 口 提 單 資 料 清 表</a>
              <a href="#" class="list-group-item h4">提 單 資 料 查 詢 作 業</a>
          </div>
        </div>
        <div class="col-md-4">
          <h3 style="background-color:#337ab7; color:white; text-align:center; border-radius:25px; padding:5px;">帳款資料維護</h3>
          <div class="list-group">
              <a href="#" class="list-group-item h4">利 潤 分 析 表</a>
              <a href="#" class="list-group-item h4">進 口 帳 收 款 明 細 表</a>
              <a href="#" class="list-group-item h4">進 口 帳 單</a>
              <a href="#" class="list-group-item h4">Debit Note</a>
              <a href="#" class="list-group-item h4">Credit Note</a>
              <a href="#" class="list-group-item h4">未 收 到  Credit  印 表</a>
              <a href="#" class="list-group-item h4">進 口 應 收 帳 款 明 細 表</a>
              <a href="#" class="list-group-item h4">異 常 報 告 表</a>
              <a href="#" class="list-group-item disabled h4">收 據 列 印</a>
              <a href="#" class="list-group-item h4">統 計 表</a>
              <a href="#" class="list-group-item h4">轉 換 ＡＣＣＳ 媒 體 檔 案</a>
          </div>
        </div>
        <div class="col-md-4">
          <h3 style="background-color:green; color:white; text-align:center; border-radius:25px; padding:5px;">基本資料維護</h3>
          <div class="list-group">
              <a href="{% url 'custadv:custadvList' %}" class="list-group-item h4">通 知 人 檔 維 護</a>
              <a href="{% url 'custcsn:custcsnList' %}" class="list-group-item h4">收 貨 人 檔 維 護</a>
              <a href="{% url 'shpr:shprList' %}" class="list-group-item h4">出 貨 人 檔 維 護
              <a href="{% url 'cneecrd:cneecrdList' %}" class="list-group-item h4">信 用 額 度 維 護</a>
              <a href="{% url 'inprmk:inprmkList' %}" class="list-group-item h4">備 註 說 明 對 照 維 護</a>
              <a href="{% url 'inpfee:inpfeeList' %}" class="list-group-item h4">費 用 名 稱 對 照 維 護</a>
              <a href="{% url 'invpars:invparsList' %}" class="list-group-item h4">發 票 參 數 設 定</a>
              <a href="{% url 'exrate:exrateList' %}" class="list-group-item h4">匯 率 查 詢 維 護</a>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

main/templates/main/messages.html
  {% if messages %}
    {% for message in messages %}
      <!--<div style="position:fixed;top:50px;right:0;width:180px;height:50px;border-radius:25%;">-->
        <!--<div {% if message.tags %} class="alert alert-{{ message.tags }} text-center alert-dismissible fade in"{% endif %} data-alert="alert" style="position:fixed;top:80px;right:0;width:160px;height:50px;border-radius:25px;">-->
        <div {% if message.tags %} class="alert alert-{{ message.tags }} text-center alert-dismissible fade in"{% endif %} data-alert="alert" style="position:fixed;top:15%;right:45%;width:200px;height:50px;border-radius:25px;">
          <!--<a class="close" data-dismiss="alert" href="#">&times;</a>-->
          <h4><strong>{{ message }}</strong></h4>
        </div>
      <!--</div>-->
    {% endfor %}
  {% endif %}

main/templates/main/test.html
{% extends 'main/base.html' %}

{% block content %}
<br><br>
<div class="container">
    <div class="col-lg-5">
        <div class="input-group my-group">
            <input type="text" class="form-control" name="snpid" placeholder="Test"/>
          <span class="input-group-append">
            <select id="lunch" class="selectpicker form-control" data-live-search="true" title="Please select a lunch ...">
                <option>Hot Dog, Fries and a Soda</option>
                <option>Burger, Shake and a Smile</option>
                <option>Sugar, Spice and all things nice</option>
                <option>Baby Back Ribs</option>
                <option>A really really long option made to illustrate an issue with the live search in an inline form</option>
            </select>
            </span>
            <span class="input-group-btn">
                <button class="btn btn-default my-group-button" type="submit">GO!</button>
            </span>
        </div>
    </div>
<div>

{% endblock %}