andyair/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('account/', include('account.urls',namespace='account')),
    path('custadv/', include('custadv.urls', namespace='custadv')),
    path('custcsn/', include('custcsn.urls', namespace='custcsn')),
    path('shpr/', include('shpr.urls', namespace='shpr')),
    path('inprmk/', include('inprmk.urls', namespace='inprmk')),
    path('inpfee/', include('inpfee.urls', namespace='inpfee')),
    path('cneecrd/', include('cneecrd.urls', namespace='cneecrd')),
    path('invpars/', include('invpars.urls', namespace='invpars')),
    path('exrate/', include('exrate.urls', namespace='exrate')),
    path('awbin/', include('awbin.urls', namespace='awbin')),
    re_path('.*', views.main),
]

base/urls.py
from django.urls import path
from main import views as mainViews
from base import views

app_name = 'base'
urlpatterns = [
    path('', mainViews.main, name='base'),
    path('custadvList/', views.custadvList, name='custadvList'),
    path('custadvCreate/', views.custadvCreate, name='custadvCreate'),
    path('custadvView/<int:pk>/', views.custadvView, name='custadvView'),
    path('custadvUpdate/<int:pk>/', views.custadvUpdate, name='custadvUpdate'),
    path('custadvDelete/<int:pk>/', views.custadvDelete, name='custadvDelete'),
    path('custqtnTabledit/', views.custqtnTabledit, name='custqtnTabledit'),
    path('custqtnNew/<int:parent_pk>/', views.custqtnNew, name='custqtnNew'),
    path('custadvData/<int:pk>/', views.custadvData, name='custadvData'),
]

custadv/urls.py
from django.urls import path
from main import views as mainViews
from custadv import views

app_name = 'custadv'
urlpatterns = [
    path('', mainViews.main, name='custadv'),
    path('custadvList/', views.custadvList, name='custadvList'),
    path('custadvCreate/', views.custadvCreate, name='custadvCreate'),
    path('custadvView/<int:pk>/', views.custadvView, name='custadvView'),
    path('custadvUpdate/<int:pk>/', views.custadvUpdate, name='custadvUpdate'),
    path('custadvDelete/<int:pk>/', views.custadvDelete, name='custadvDelete'),
    path('custqtnTabledit/', views.custqtnTabledit, name='custqtnTabledit'),
    path('custqtnNew/<int:parent_pk>/', views.custqtnNew, name='custqtnNew'),
    path('custadvData/<int:pk>/', views.custadvData, name='custadvData'),
]

custadv/models.py
from django.db import models
from main.models import WhoColumns

class Custadv(WhoColumns):
    cuno = models.CharField(max_length=10, unique=True)        #客戶代號
    ipntfy = models.CharField(max_length=30, blank=True)       #應通知公司
    ipntfym = models.CharField(max_length=30, blank=True)      #貨主聯絡人
    ipntftl = models.CharField(max_length=20, blank=True)      #電話號碼
    ipntffx = models.CharField(max_length=20, blank=True)      #傳真號碼
    ipmnspay = models.BooleanField(blank=True)                 #是否月結
    ipentry = models.BooleanField(blank=True)                  #是否報關
    iprtord = models.BooleanField(blank=True)                  #是否進口指定貨
    ipntfmk = models.CharField(max_length=30, blank=True)      #備註

    def __str__(self):
        return self.cuno + '-' + self.ipntfy + '電話:' + self.ipntftl + '傳真:' + self.ipntffx

class Custqtn(WhoColumns):
    custadv = models.ForeignKey(Custadv, on_delete=models.CASCADE)
    org = models.CharField(max_length=3)                       #ORG
    qtndd = models.DateTimeField(blank=True)                   #日期
    qtns = models.CharField(max_length=60, blank=True)         #說明
    trashed_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.org + '--' + self.qtndd.strftime('%Y-%m-%d')

base/forms.py
from django import forms
from base.models import Custadv, Custqtn


class CustadvForm(forms.ModelForm):
    cuno = forms.CharField(label='客戶代號', min_length=6, max_length=10, required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntfy = forms.CharField(label='應通知公司', max_length=30, required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntfym = forms.CharField(label='貨主聯絡人', max_length=30, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntftl = forms.CharField(label='電話號碼', max_length=20, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntffx = forms.CharField(label='傳真號碼', max_length=20, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipmnspay = forms.BooleanField(label='是否月結', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    ipentry = forms.BooleanField(label='是否報關', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    iprtord = forms.BooleanField(label='是否進口指定貨', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    ipntfmk = forms.CharField(label='備註', max_length=30, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Custadv
        fields = ['cuno', 'ipntfy', 'ipntfym', 'ipntftl', 'ipntffx', 'ipmnspay', 'ipentry', 'iprtord', 'ipntfmk']

class CustqtnForm(forms.ModelForm):

    org = forms.CharField(label='ORG', max_length=3, widget=forms.TextInput(attrs={'class':'form-control'}))
    qtndd = forms.DateField(label='日期', widget=forms.TextInput(attrs={'readonly':'readonly','class':'form-control'}))
    qtns = forms.CharField(label='說明', max_length=60, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Custqtn
        fields = ['org', 'qtndd', 'qtns']

custadv/forms.py
from django import forms
from custadv.models import Custadv, Custqtn


class CustadvForm(forms.ModelForm):
    cuno = forms.CharField(label='客戶代號', min_length=6, max_length=10, required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntfy = forms.CharField(label='應通知公司', max_length=30, required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntfym = forms.CharField(label='貨主聯絡人', max_length=30, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntftl = forms.CharField(label='電話號碼', max_length=20, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipntffx = forms.CharField(label='傳真號碼', max_length=20, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))
    ipmnspay = forms.BooleanField(label='是否月結', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    ipentry = forms.BooleanField(label='是否報關', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    iprtord = forms.BooleanField(label='是否進口指定貨', widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False)
    ipntfmk = forms.CharField(label='備註', max_length=30, required=False, widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Custadv
        fields = ['cuno', 'ipntfy', 'ipntfym', 'ipntftl', 'ipntffx', 'ipmnspay', 'ipentry', 'iprtord', 'ipntfmk']

class CustqtnForm(forms.ModelForm):

    org = forms.CharField(label='ORG', max_length=3, widget=forms.TextInput(attrs={'class':'tabledit-input form-control input-sm'}))
    qtndd = forms.DateField(label='日期', widget=forms.TextInput(attrs={'readonly':'readonly','class':'tabledit-input form-control input-sm'}))
    qtns = forms.CharField(label='說明', max_length=60, required=False, widget=forms.TextInput(attrs={'class':'tabledit-input form-control input-sm'}))

    class Meta:
        model = Custqtn
        fields = ['org', 'qtndd', 'qtns']

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from base.models import Custadv, Custqtn
from base.forms import CustadvForm, CustqtnForm

@login_required
def custadvList(request, template_name='base/custadvList.html'):
    custadvs = Custadv.objects.all()
    ctx = {}
    ctx['custadvs'] = custadvs
    ctx['title'] = 'List'
    return render(request, template_name, ctx)

@login_required
def custadvCreate(request, template_name='base/custadvForm.html'):
    form = CustadvForm(request.POST or None)
    if form.is_valid():
        new_cust = form.save(commit=False)
        new_cust.created_by = request.user
        new_cust.last_updated_by = request.user
        new_cust.save()
        messages.success(request, '資料已新增！')
        return redirect('base:custadvUpdate', new_cust.id)
    ctx = {}
    ctx['form'] = form
    ctx['title'] = 'New'
    return render(request, template_name, ctx)

@login_required
def custadvView(request, pk, template_name='base/custadvView.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'View'
    return render(request, template_name, ctx)

@login_required
def custadvUpdate(request, pk, template_name='base/custadvForm.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    form = CustadvForm(request.POST or None, instance=custadv)
    if form.is_valid():
        custadv_obj = form.save(commit=False)
        custadv_obj.last_updated_by = request.user
        custadv_obj.save()
        messages.success(request, '資料已更新！')
        return redirect('base:custadvUpdate', custadv.id)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['form'] = form
    ctx['title'] = 'Edit'
    return render(request, template_name, ctx)

@login_required
def custadvDelete(request, pk, template_name='base/custadvDelete.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    if request.method == 'POST':
        custadv.delete()
        messages.success(request, '資料已刪除！')
        return redirect('base:custadvList')
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'Delete'
    return render(request, template_name, ctx)

@login_required
def custadvData(request, pk):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    if request.POST.get('requestData') == 'master':
        ctx['custadv'] = custadv
        template_name = 'base/custMaster.html'
    else:
        ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
        template_name = 'base/custDetail.html'
    return render(request, template_name, ctx)

@login_required
def custqtnNew(request, parent_pk, template_name='base/custqtnNew.html'):
    custadv = get_object_or_404(Custadv, pk=parent_pk)
    form = CustqtnForm(request.POST or None)
    if form.is_valid():
        custqtn = form.save(commit=False)
        custqtn.custadv = custadv
        custqtn.created_by = request.user
        custqtn.last_updated_by = request.user
        custqtn.save()
        messages.success(request, '明細資料已新增！')
        return redirect('base:custadvUpdate', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["custadv"] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = ' New Detail'
    return render(request, template_name, ctx)

@login_required
def custqtnTabledit(request):
    if request.method == 'POST':
        custqtn = get_object_or_404(Custqtn, pk=request.POST.get('id'))
        if request.POST.get('action') == 'edit':
            custqtn.org = request.POST.get('org')
            custqtn.qtndd = datetime.strptime(request.POST.get('qtndd'),"%Y-%m-%d").date()
            custqtn.qtns = request.POST.get('qtns')
            custqtn.last_updated_by = request.user
            custqtn.save()
            messages.success(request, '明細資料已更新！')
        if request.POST.get('action') == 'delete':
            custqtn.delete()
            messages.success(request, '明細資料已刪除！')

        django_messages = []
        for message in messages.get_messages(request):
            django_messages.append({
                "level": message.level,
                "message": message.message,
                "tags": message.tags,
            })
        ctx = {}
        ctx['request'] = request.POST
        ctx['messages'] = django_messages

        return JsonResponse(ctx)
        # return JsonResponse(request.POST)
    else:
        return render(request, 'main/main.html')

custadv/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from custadv.models import Custadv, Custqtn
from custadv.forms import CustadvForm, CustqtnForm

@login_required
def custadvList(request, template_name='custadv/custadvList.html'):
    custadvs = Custadv.objects.all()
    ctx = {}
    ctx['custadvs'] = custadvs
    ctx['title'] = 'List'
    return render(request, template_name, ctx)

@login_required
def custadvCreate(request, template_name='custadv/custadvForm.html'):
    form = CustadvForm(request.POST or None)
    if form.is_valid():
        new_cust = form.save(commit=False)
        new_cust.created_by = request.user
        new_cust.last_updated_by = request.user
        new_cust.save()
        messages.success(request, '資料已新增！')
        return redirect('custadv:custadvUpdate', new_cust.id)
    ctx = {}
    ctx['form'] = form
    ctx['title'] = 'New'
    return render(request, template_name, ctx)

@login_required
def custadvView(request, pk, template_name='custadv/custadvView.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'View'
    return render(request, template_name, ctx)

@login_required
def custadvUpdate(request, pk, template_name='custadv/custadvForm.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    form = CustadvForm(request.POST or None, instance=custadv)
    if form.is_valid():
        custadv_obj = form.save(commit=False)
        custadv_obj.last_updated_by = request.user
        custadv_obj.save()
        messages.success(request, '資料已更新！')
        return redirect('custadv:custadvUpdate', custadv.id)
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['form'] = form
    ctx['title'] = 'Edit'
    return render(request, template_name, ctx)

@login_required
def custadvDelete(request, pk, template_name='custadv/custadvDelete.html'):
    custadv = get_object_or_404(Custadv, pk=pk)
    if request.method == 'POST':
        custadv.delete()
        messages.success(request, '資料已刪除！')
        return redirect('custadv:custadvList')
    ctx = {}
    ctx['custadv'] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = 'Delete'
    return render(request, template_name, ctx)

@login_required
def custadvData(request, pk):
    custadv = get_object_or_404(Custadv, pk=pk)
    ctx = {}
    if request.POST.get('requestData') == 'master':
        ctx['custadv'] = custadv
        template_name = 'custadv/custMaster.html'
    else:
        ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
        template_name = 'custadv/custDetail.html'
    return render(request, template_name, ctx)

@login_required
def custqtnNew(request, parent_pk, template_name='custadv/custqtnNew.html'):
    custadv = get_object_or_404(Custadv, pk=parent_pk)
    form = CustqtnForm(request.POST or None)
    if form.is_valid():
        custqtn = form.save(commit=False)
        custqtn.custadv = custadv
        custqtn.created_by = request.user
        custqtn.last_updated_by = request.user
        custqtn.save()
        messages.success(request, '明細資料已新增！')
        return redirect('custadv:custadvUpdate', parent_pk)
    ctx = {}
    ctx["form"] = form
    ctx["custadv"] = custadv
    ctx['custqtns'] = Custqtn.objects.filter(custadv=custadv)
    ctx['title'] = ' New Detail'
    return render(request, template_name, ctx)

@login_required
def custqtnTabledit(request):
    if request.method == 'POST':
        custqtn = get_object_or_404(Custqtn, pk=request.POST.get('id'))
        if request.POST.get('action') == 'edit':
            custqtn.org = request.POST.get('org')
            custqtn.qtndd = datetime.strptime(request.POST.get('qtndd'),"%Y-%m-%d").date()
            custqtn.qtns = request.POST.get('qtns')
            custqtn.last_updated_by = request.user
            custqtn.save()
            messages.success(request, '明細資料已更新！')
        if request.POST.get('action') == 'delete':
            custqtn.delete()
            messages.success(request, '明細資料已刪除！')

        django_messages = []
        for message in messages.get_messages(request):
            django_messages.append({
                "level": message.level,
                "message": message.message,
                "tags": message.tags,
            })
        ctx = {}
        ctx['request'] = request.POST
        ctx['messages'] = django_messages

        return JsonResponse(ctx)
        # return JsonResponse(request.POST)
    else:
        return render(request, 'main/main.html')

base/templates/base/custadvData.html
<div style="background-color:white; border-radius:10px;">
  <div id="custMaster">
  
  </div>
  <div id="custDetail" style="background-color:white">
      <table class="table table-striped table-bordered table-responsive">
      <thead>
        <tr>
          <th style="width: 1%;vertical-align: middle;">#ID</th>
          <th style="width: 1%;vertical-align: middle;">No.</th>
          <th style="vertical-align: middle">ORG</th>
          <th style="vertical-align: middle">日期</th>
          <th style="vertical-align: middle">說明</th>
        </tr>
      </thead>
      <tbody>

      </tbody>
    </table>
  </div>
</div>
<script>
  $(document).ready(function() {

      $.post("{% url 'base:custadvData' custadv.id %}",{'requestData':'master'},   //post函数到后端
        function(data,status){                                                     //回调函数
             $("#custMaster").html(data);                                          //将id为custMaster的标签的html替换为返回的data
      });
      $.post("{% url 'base:custadvData' custadv.id %}",{'requestData':'detail'},   //post函数到后端
        function(data,status) {                                                     //回调函数
            $("#custDetail tbody").html(data);                                         //将id为custMaster的标签的html替换为返回的data
      });
  })
</script>

base/templates/base/custadvDelete.html
{% extends "base/base.html" %}

{% block app_content %}

{% include "base/nav.html" with custadv=custadv title=title %}
{% include 'main/messages.html' %}
{% include "base/custadvData.html" %}
<form method="post">{% csrf_token %}
    <h3>
    Are you sure you want to delete "{{ custadv }}" ?<br><br>

    <input class="btn btn-danger btn-md" type="submit" value="刪除" />
    <a class="btn btn-primary btn-md" href="{% url 'base:custadvList' %}">取消</a>
    </h3>
</form>

{% endblock app_content %}

base/templates/base/custadvForm.html
{% extends "base/base.html" %}

{% block app_content %}

{% include "base/nav.html" with custadv=custadv title=title %}
{% include 'main/messages.html' %}
<div id="div_messages" class="text-center align-middle" style="position:fixed;top:60px;right:0;width:160px;height:50px;border-radius:25px;"></div>
<div>
  <form id="masterForm" role="form" method="post">{% csrf_token %}

    {{ form.non_field_errors }}
    <div>
      <div class="form-row">
        <div class="form-group col-md-3">
          {{ form.cuno.errors}}
          {{ form.cuno.label_tag}}
          {{ form.cuno }}
        </div>
        <div class="form-group col-md-9">
          {{ form.ipntfy.errors}}
          {{ form.ipntfy.label_tag}}
          {{ form.ipntfy }}
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4">
          {{ form.ipntfym.errors}}
          {{ form.ipntfym.label_tag}}
          {{ form.ipntfym }}
        </div>
        <div class="form-group col-md-4">
          {{ form.ipntftl.errors}}
          {{ form.ipntftl.label_tag}}
          {{ form.ipntftl }}
        </div>
        <div class="form-group col-md-4">
          {{ form.ipntffx.errors}}
          {{ form.ipntffx.label_tag}}
          {{ form.ipntffx }}
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4 form-check form-check-inline">
          {{ form.ipmnspay.errors}}
          <label>{{ form.ipmnspay }}{{ form.ipmnspay.label }}</label>
        </div>
        <div class="form-group col-md-4 form-check form-check-inline">
          {{ form.ipentry.errors}}
          <label>{{ form.ipentry }}{{ form.ipentry.label }}</label>
        </div>
        <div class="form-group col-md-4 form-check form-check-inline">
          {{ form.iprtord.errors}}
          <label>{{ form.iprtord }}{{ form.iprtord.label }}</label>
        </div>
      </div>
      <div class="form-row align-text-top">
        <div class="form-group col-md-8">
            {{ form.ipntfmk.errors}}
            {{ form.ipntfmk.label_tag}}
            {{ form.ipntfmk }}
        </div>
          <div class="form-group col-md-4" style="position:fixed;top:110px;right:263px;width:160px;height:50px;text-align:right">
              <input class="btn btn-success btn-md" type="submit" value="存檔"/>
              <!--
              {% if custadv %}
                <a class="btn btn-warning btn-md" href="{% url 'base:custadvUpdate' custadv.id %}">取消</a>
              {% endif %}
              -->
              <a class="btn btn-primary btn-md" href="{% url 'base:custadvList' %}">離開</a>
          </div>
      </div>
    </div>
  </form>
  <div id="custqtnEdit" class="form-row">
    <table style="margin-left: 1em; width: 97.5%;" id="custqtn" class="table table-hover table-bordered table-responsive table-condensed">
      <thead>
        <tr>
          <th style="display:none;width: 1%;vertical-align: middle;">#ID</th>
          <th style="width: 1%;vertical-align: middle;">No.</th>
          <th style="vertical-align: middle">ORG</th>
          <th style="vertical-align: middle">日期</th>
          <th style="vertical-align: middle">說明</th>
          <th class="text-center" style="width:5%">
            {% if custadv %}
              <input type="hidden" id="Url" data-url="{% url 'base:custqtnNew' custadv.id %}" />
              <button onclick="newqtnForm()" class="btn btn-info btn-block btn-sm active" id="newqtn">
              <span class="glyphicon glyphicon-plus"></span>&nbsp;<b>Line</b></button>
            {% endif %}
          </th>
        </tr>
      </thead>
      <tbody style="background-color:white">
          {% for custqtn in custqtns %}
            <tr>
            <td style="display:none">{{ custqtn.id }}</td>
            <td>{{ forloop.counter }}</td>
            <td>{{ custqtn.org }}</td>
            <td>{{ custqtn.qtndd|date:"Y-m-d" }}</td>
            <td>{{ custqtn.qtns }}</td>
            </tr>
          {% endfor %}
      </tbody>
    </table>
  </div>
  <div id="custqtnNew" class="form-row"></div>
</div>
<script>
 
    function newqtnForm() {
        var url = $("#Url").attr("data-url");
        $.get(url, {'request': 'custqtn'}, function (data, status) {
            $('#custqtnEdit').hide();
            $('#custqtnNew').html(data);
        });
    }
    
    $(document).ready(function() {

        $('#masterForm input[type="submit"]').prop('disabled', true);

        $('#masterForm').bind('change keyup', function () {
            $('#masterForm input[type="submit"]').prop('disabled', false);
            console.log('changed');
        });
        
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
            });
        
        $('#custqtn').Tabledit({
            url: '{% url "base:custqtnTabledit" %}',
            restoreButton: false,
            hideIdentifier: true,
            columns: {
                identifier: [0, 'id'],
                editable: [[2, 'org'], [3, 'qtndd'], [4, 'qtns']]
            },
            onDraw: function () {
                // Select all inputs of second column and apply datepicker each of them
                $('table tr td:nth-child(4)').each(function () {
                    $(this).datepicker({
                        format: "yyyy-mm-dd",
                        todayBtn: "linked",
                        autoclose: true,
                        todayHighlight: true,
                    });
                });
            },
            onSuccess: function (data, textStatus, jqXHR) {
                console.log('onSuccess(data, textStatus, jqXHR)');
                console.log(data);
                console.log(textStatus);
                console.log(jqXHR);
                if (data['request'].action == 'delete')
                 {
                  $('#'+data['request'].id).remove();
                 }
                 update_messages(data.messages);
                 $(".alert").fadeOut(3000);
            },
            onFail: function (jqXHR, textStatus, errorThrown) {
                console.log('onFail(jqXHR, textStatus, errorThrown)');
                console.log(jqXHR);
                console.log(textStatus);
                console.log(errorThrown);
            },
            onAlways: function () {
                console.log('onAlways()');
            },
            onAjax: function (action, serialize) {
                console.log('onAjax(action, serialize)');
                console.log(action);
                console.log(serialize);
            }
        });

        $('#custqtn thead tr th:last-child').remove();
        
    });
    function update_messages(messages) {
        $("#div_messages").html("");
        $.each(messages, function (i, m) {
            var html = "<div class='alert alert-"+m.tags+" alert-dismissible fade in'>"+"<strong>"+m.message+"</strong>"+"</div>";
            $("#div_messages").append(html);
        });
    }
</script>

{% endblock app_content %}

base/templates/base/custadvList.html
{% extends "base/base.html" %}

{% block app_content %}
{% include "base/nav.html" with title=title %}
{% include 'main/messages.html' %}
<div>
  <table class="table table-striped table-bordered table-responsive table-condensed" id="custadvList">
    <thead>
      <tr>
        <th style="vertical-align: middle">客戶代號</th>
        <th style="vertical-align: middle">應通知公司</th>
        <th style="vertical-align: middle">貨主聯絡人</th>
        <th style="vertical-align: middle">電話號碼</th>
        <th id="newCust" class="text-center">
          <a href="{% url 'base:custadvCreate' %}" class="btn btn-block btn-info btn-sm active">
            <span class="glyphicon glyphicon-plus"></span><b>&nbsp;New</b></a>
        </th>
      </tr>
    </thead>
    <tbody style="background-color:white">
      {% for custadv in custadvs %}
        <tr>
          <td>{{ custadv.cuno }}</td>
          <td>{{ custadv.ipntfy }}</td>
          <td>{{ custadv.ipntfym }}</td>
          <td>{{ custadv.ipntftl }}</td>
          <td style="text-align: center;white-space: nowrap; width: 12%;">
            <div class="tabledit-toolbar btn-toolbar">
              <div class="btn-group btn-group-sm" style="float: none;">
                <a href="{% url 'base:custadvView' custadv.id %}" class="tabledit-edit-button btn btn-sm btn-default "><span class="glyphicon glyphicon-eye-open"></span></a>
                <a href="{% url 'base:custadvUpdate' custadv.id %}" class="tabledit-edit-button btn btn-sm btn-default "><span class="glyphicon glyphicon-pencil"></span></a>
                <a href="{% url 'base:custadvDelete' custadv.id %}" class="tabledit-delete-button btn btn-sm btn-default "><span class="glyphicon glyphicon-trash"></span></a>
              </div>
            </div>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#custadvList').DataTable({
            "searching": true,
            "ordering": true,
            "paging": true,
            "order": [[ 1, "asc" ]],
            "columnDefs": [
                {
                    "targets": 4,
                    "searchable": false,
                    "orderable": false
                }
            ]
        });
        $('#newCust').removeClass('sorting_disabled').removeAttr('aria-label').css('padding','8px');
    });
    
</script>

{% endblock app_content %}